export const PRODUCTS = {
  'atlas-ats24ifb100-23-8-inch-ips-fhd-100hz-monitor': {
    slug: 'atlas-ats24ifb100-23-8-inch-ips-fhd-100hz-monitor',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS ATS24IFB100 23.8-Inch IPS FHD Monitor with 100Hz Refresh Rate',
    subtitle: 'Premium IPS A+ Grade panel with Full HD resolution and 100Hz refresh rate for smooth, color-accurate visuals every day.',
    heroFloat: ['ATS24IFB100', 'Monitor'],
    image: '/assets/images/products/ats24ifb100-main.png',
    chips: [
      { value: '23.8-inch IPS A+ Grade panel with 1920×1080 Full HD resolution for sharp, vivid visuals', label: 'Premium IPS Display' },
      { value: '100Hz refresh rate for smoother motion and reduced blur in gaming and daily use', label: '100Hz Refresh Rate' },
      { value: '178° horizontal and vertical viewing angles for consistent color from any position', label: 'Wide Viewing Angle' },
    ],
    overviewBody: 'Premium IPS Display — 23.8-inch A+ Grade IPS panel with 1920×1080 Full HD resolution delivers vivid, true-to-life colors for work, media, and casual gaming. 100Hz Refresh Rate — Smoother scrolling and reduced motion blur compared to standard 60Hz monitors. Wide Viewing Angle — 178° horizontal and vertical viewing angles ensure consistent image quality from virtually any position. Dual Connectivity — HDMI and VGA inputs for seamless compatibility with both modern and legacy devices. Long-term Reliability — Backed by a 3-year warranty for worry-free daily use.',
    overviewStats: [{ value: 'ATS24IFB100', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'Premium IPS A+ Display', body: '23.8-inch A+ Grade IPS panel with 1920×1080 Full HD resolution for vivid, accurate colors from edge to edge' },
      { title: '100Hz Refresh Rate', body: 'Smoother motion and reduced blur compared to 60Hz — better for scrolling, gaming, and fast content' },
      { title: 'Dual Connectivity', body: 'HDMI and VGA inputs for seamless compatibility with modern PCs, laptops, and older devices' },
    ],
    gallery: [
      { src: '/assets/images/products/ats24ifb100-main.png', alt: 'ATLAS ATS24IFB100 - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats24ifb100-angle.jpg', alt: 'ATLAS ATS24IFB100 - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats24ifb100-detail.jpg', alt: 'ATLAS ATS24IFB100 - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats24ifb100-detail.jpg', alt: 'ATLAS ATS24IFB100 - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'Display', items: ['23.8-inch IPS A+ Grade panel (≈ 60.5 cm)', '1920 × 1080 Full HD resolution', 'White LED backlight', '1000:1 contrast ratio', '250–300 nits brightness'] },
      { title: 'Performance', items: ['100Hz refresh rate', '5ms response time', '178° horizontal viewing angle', '178° vertical viewing angle'] },
      { title: 'Connectivity', items: ['HDMI input', 'VGA input', 'No built-in speakers'] },
      { title: 'Power & Warranty', items: ['100–260V, 50/60Hz universal input', 'UK type power adapter', '3-year warranty'] },
    ],
    specTable: [
      ['SKU', 'ATS24IFB100'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Display Size', '23.8 inch (≈ 60.5 cm)'], ['Panel Type', 'IPS (A+ Grade)'], ['Backlight', 'White LED'],
      ['Resolution', '1920 × 1080 (Full HD)'], ['Refresh Rate', '100Hz'], ['Response Time', '5ms'],
      ['Contrast Ratio', '1000:1'], ['Brightness', '250–300 nits'], ['Viewing Angle', '178° horizontal / 178° vertical'],
      ['Input Ports', 'HDMI, VGA'], ['Speaker', 'None'], ['Power Input', '100–260V, 50/60Hz'],
      ['Power Adapter', 'UK type plug'], ['Warranty', '3 Years'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas ATS24IFB100 – 23.8 Inch IPS FHD 100Hz Monitor | 3-Year Warranty',
      description: 'Buy the Atlas ATS24IFB100 23.8-inch IPS A+ Grade 100Hz Full HD monitor in Bangladesh. 178° viewing angles, HDMI & VGA, 5ms response, 3-year warranty. Perfect for office, gaming, and daily use.',
      keywords: 'Atlas ATS24IFB100, 24 inch IPS monitor Bangladesh, 23.8 inch 100Hz monitor, Full HD IPS monitor Bangladesh, buy 24 inch monitor Bangladesh, 100Hz monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-ats24ifb100-23-8-inch-ips-fhd-100hz-monitor',
      image: '/assets/images/products/ats24ifb100-main.png',
    },
  },

  'atlas-21-5-full-hd-led-monitor-1920x1080-60hz-hdmi-vga-5ms-white': {
    slug: 'atlas-21-5-full-hd-led-monitor-1920x1080-60hz-hdmi-vga-5ms-white',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS 21.5" Full HD LED Monitor – 1920×1080, 60Hz, HDMI + VGA, 5ms Response',
    subtitle: 'Full HD clarity in a slim white frameless design — built for office, study, and everyday use.',
    heroFloat: ['ATS22FW060', 'Monitor'],
    image: '/assets/images/products/ats22fw060-main.png',
    chips: [
      { value: '1920×1080 Full HD resolution with 16:9 aspect ratio for crisp, detailed visuals', label: 'Full HD Display' },
      { value: '5ms response time for smooth, blur-free performance across daily tasks', label: '5ms Response Time' },
      { value: '178° horizontal and vertical viewing angles for consistent color from any position', label: 'Wide Viewing Angle' },
    ],
    overviewBody: 'Full HD Display — 21.5-inch screen with 1920×1080 resolution and 16:9 aspect ratio for sharp, detailed visuals in every task. Fast Response Time — 5ms (OD) response for smooth, blur-free performance during work, media, and light gaming. Wide Viewing Angle — 178° horizontal and vertical viewing angles ensure consistent image quality from any seat. Slim Frameless Design — White finish with minimal bezels for a clean, modern desktop look. Dual Connectivity — HDMI and VGA ports for easy compatibility with any PC, laptop, or older device.',
    overviewStats: [{ value: 'ATS22FW060', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'Full HD 1920×1080 Display', body: '21.5-inch panel with 16:9 aspect ratio — sharp, clear visuals for work, study, and everyday media' },
      { title: 'Slim Frameless White Design', body: 'Minimal bezels and white finish give your desk a clean, modern look with tilt-adjustable stand' },
      { title: 'HDMI & VGA Connectivity', body: 'Two input options for seamless compatibility with modern laptops, desktops, and older PCs' },
    ],
    gallery: [
      { src: '/assets/images/products/ats22fw060-main.png', alt: 'ATLAS 21.5" Full HD LED Monitor - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats22fw060-angle.jpg', alt: 'ATLAS 21.5" Full HD LED Monitor - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats22fw060-detail.jpg', alt: 'ATLAS 21.5" Full HD LED Monitor - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats22fw060-detail.jpg', alt: 'ATLAS 21.5" Full HD LED Monitor - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'Display', items: ['21.5-inch LED panel', '1920 × 1080 Full HD resolution', '16:9 aspect ratio', '~16.7 million colors', '~1000:1 contrast ratio', '~250 cd/m² brightness'] },
      { title: 'Performance', items: ['60Hz refresh rate', '5ms response time (OD)', '178° horizontal viewing angle', '178° vertical viewing angle', 'Anti-glare screen'] },
      { title: 'Connectivity', items: ['HDMI input', 'VGA input', 'DC power input'] },
      { title: 'Design', items: ['Slim frameless design', 'White color', 'Tilt-adjustable stand', 'Suitable for office, study, and basic gaming', '3-year warranty'] },
    ],
    specTable: [
      ['SKU', 'ATS22FW060'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Screen Size', '21.5 inch'], ['Resolution', '1920 × 1080 (Full HD)'], ['Aspect Ratio', '16:9'],
      ['Panel Type', 'LED'], ['Color Support', '~16.7 Million Colors'], ['Refresh Rate', '60Hz'],
      ['Response Time', '5ms (OD)'], ['Brightness', '~250 cd/m²'], ['Contrast Ratio', '~1000:1'],
      ['Viewing Angle', '178° horizontal / 178° vertical'], ['HDMI', 'Yes'], ['VGA', 'Yes'],
      ['Power Input', 'DC'], ['Design', 'Slim / Frameless, White'], ['Tilt', 'Yes'], ['Anti-glare', 'Yes'],
      ['Warranty', '3 Years'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas 21.5 Inch Full HD LED Monitor – 1920×1080, 60Hz, HDMI + VGA, 5ms',
      description: 'Buy the Atlas 21.5-inch Full HD LED monitor in Bangladesh. 1920x1080 resolution, 60Hz, 5ms response, HDMI & VGA, slim white design with anti-glare screen. Perfect for office, study, and daily use.',
      keywords: 'Atlas 21.5 inch monitor Bangladesh, Full HD LED monitor Bangladesh, 21.5 inch 1080p monitor, HDMI VGA monitor Bangladesh, white monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-21-5-full-hd-led-monitor-1920x1080-60hz-hdmi-vga-5ms-white',
      image: '/assets/images/products/ats22fw060-main.png',
    },
  },

  'atlas-ats22vfw100e-elite-series-21-5-100hz-full-hd-led-monitor': {
    slug: 'atlas-ats22vfw100e-elite-series-21-5-100hz-full-hd-led-monitor',
    category: 'Monitor',
    eyebrow: 'Elite Series',
    title: 'ATLAS ATS22VFW100E Elite Series 21.5" 100Hz Full HD LED Monitor',
    subtitle: 'Dynamic LED backlight, 3000:1 contrast ratio, and 100Hz refresh rate — built for vivid, smooth visuals every day.',
    heroFloat: ['ATS22VFW100E', 'Monitor'],
    image: '/assets/images/products/ats22vfw100e-main.png',
    chips: [
      { value: '1920×1080 Full HD with 3000:1 contrast ratio and dynamic LED backlighting for deep, rich visuals', label: 'High Contrast Full HD' },
      { value: '100Hz refresh rate for smoother motion and reduced blur in daily use and gaming', label: '100Hz Refresh Rate' },
      { value: 'Anti-glare flat panel with slim modern design and lightweight build for any workspace', label: 'Slim Elite Design' },
    ],
    overviewBody: 'High Contrast Full HD — 21.5-inch Full HD panel with a standout 3000:1 contrast ratio and dynamic LED backlighting for deep blacks and vivid colors. 100Hz Refresh Rate — Smoother motion compared to standard 60Hz displays, ideal for fast-moving content and daily gaming. Anti-Glare Surface — Reduces reflections for comfortable extended use in any lighting. Slim Elite Design — Modern flat-panel build with lightweight construction fits any desktop or office setup. Dual Connectivity — HDMI and VGA ports for easy plug-in with any PC, laptop, or older device.',
    overviewStats: [{ value: 'ATS22VFW100E', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: '3000:1 Contrast Ratio', body: 'Dynamic LED backlighting delivers deeper blacks and richer colors than standard monitors — vivid visuals in every scene' },
      { title: '100Hz Smooth Refresh', body: 'Smoother scrolling and reduced motion blur over 60Hz panels — better for fast content, gaming, and daily tasks' },
      { title: 'Slim & Modern Build', body: 'Flat panel, lightweight design with anti-glare surface fits cleanly into any office, study, or home workspace' },
    ],
    gallery: [
      { src: '/assets/images/products/ats22vfw100e-main.png', alt: 'ATLAS ATS22VFW100E Elite Series - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats22vfw100e-angle.jpg', alt: 'ATLAS ATS22VFW100E Elite Series - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats22vfw100e-detail.jpg', alt: 'ATLAS ATS22VFW100E Elite Series - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats22vfw100e-detail.jpg', alt: 'ATLAS ATS22VFW100E Elite Series - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'Display', items: ['21.5-inch flat panel, LED backlit', '1920 × 1080 Full HD resolution', '16:9 aspect ratio', '100Hz refresh rate', '3000:1 contrast ratio', '16.7 million colours', 'Anti-glare surface treatment'] },
      { title: 'Performance', items: ['Fast response time', 'Dynamic LED backlighting', 'Smooth 100Hz motion', 'Reduced motion blur'] },
      { title: 'Connectivity', items: ['1 × HDMI port', '1 × VGA port'] },
      { title: 'Design & Power', items: ['Slim & modern flat screen design', 'Lightweight build', 'Energy efficient', 'Low power consumption LED technology', '3-year warranty'] },
    ],
    specTable: [
      ['SKU', 'ATS22VFW100E'], ['Series', 'Elite Series'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Screen Size', '21.5 inch'], ['Display Type', 'LED Backlit'], ['Panel Type', 'Flat Panel'],
      ['Resolution', '1920 × 1080 (Full HD)'], ['Aspect Ratio', '16:9'], ['Refresh Rate', '100Hz'],
      ['Response Time', 'Fast Response'], ['Color Support', '16.7 Million Colours'], ['Contrast Ratio', '3000:1'],
      ['Surface Treatment', 'Anti-Glare'], ['Backlight Technology', 'Dynamic LED Backlighting'],
      ['HDMI', '1 × HDMI Port'], ['VGA', '1 × VGA Port'], ['Power', 'Energy Efficient, Low Power Consumption'],
      ['Design', 'Slim & Modern, Lightweight, Flat Screen'],
      ['Warranty', '3 Years'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas ATS22VFW100E Elite – 21.5 Inch 100Hz Full HD LED Monitor',
      description: 'Buy the Atlas Elite Series ATS22VFW100E 21.5-inch 100Hz Full HD LED monitor in Bangladesh. 1920x1080, 3000:1 contrast, dynamic LED backlight, anti-glare, HDMI & VGA. Slim modern design.',
      keywords: 'Atlas ATS22VFW100E, Elite Series monitor Bangladesh, 21.5 inch 100Hz monitor, Full HD LED monitor Bangladesh, 3000:1 contrast monitor',
      canonical: 'https://www.atlascomparts.com/atlas-ats22vfw100e-elite-series-21-5-100hz-full-hd-led-monitor',
      image: '/assets/images/products/ats22vfw100e-main.png',
    },
  },

  'atlas-22-hd-led-monitor-1610-aspect-ratio-vga-hdmi-input': {
    slug: 'atlas-22-hd-led-monitor-1610-aspect-ratio-vga-hdmi-input',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS 22" HD LED Monitor 16:10 Aspect Ratio, VGA & HDMI Input',
    subtitle: 'High Definition Display - 22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals',
    heroFloat: ['AT22T', 'Monitor'],
    image: '/assets/images/products/monitor-22-hd-main.png',
    chips: [
      { value: '22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals', label: 'High Definition Display' },
      { value: '5ms response time for smooth performance, ideal for gaming and multimedia', label: 'Fast Response Time' },
      { value: 'Energy-efficient LED backlight for bright, vibrant images while reducing power consumption', label: 'LED Backlight Technology' },
    ],
    overviewBody: 'High Definition Display - 22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals. Fast Response Time - 5ms response time for smooth performance, ideal for gaming and multimedia. LED Backlight Technology - Energy-efficient LED backlight for bright, vibrant images while reducing power consumption. Versatile Connectivity - Multiple input options, including VGA, HDMI, and DC power port, ensuring compatibility with various devices. VESA Mount Compatibility - Supports VESA mounting, offering flexible installation options for a clean and adjustable setup.',
    overviewStats: [{ value: 'AT22T', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'High Definition Display', body: '22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals' },
      { title: 'Fast Response Time', body: '5ms response time for smooth performance, ideal for gaming and multimedia' },
      { title: 'LED Backlight Technology', body: 'Energy-efficient LED backlight for bright, vibrant images while reducing power consumption' },
    ],
    gallery: [
      { src: '/assets/images/products/monitor-22-hd-main.png', alt: 'ATLAS 22" HD LED Monitor - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/monitor-22-hd-angle.jpg', alt: 'ATLAS 22" HD LED Monitor - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/monitor-22-hd-detail.jpg', alt: 'ATLAS 22" HD LED Monitor - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/monitor-22-hd-main.png', alt: 'ATLAS 22" HD LED Monitor - Overview', caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: 'High Definition Display', items: ['22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals'] },
      { title: 'Fast Response Time', items: ['5ms response time for smooth performance, ideal for gaming and multimedia'] },
      { title: 'LED Backlight Technology', items: ['Energy-efficient LED backlight for bright, vibrant images while reducing power consumption'] },
      { title: 'Versatile Connectivity', items: ['Multiple input options, including VGA, HDMI, and DC power port, ensuring compatibility with various devices'] },
    ],
    specTable: [
      ['SKU', 'AT22T'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['High Definition Display', '22-inch screen with 1680 x 1050 resolution and a 16:10 aspect ratio for clear and sharp visuals'],
      ['Fast Response Time', '5ms response time for smooth performance, ideal for gaming and multimedia'],
      ['LED Backlight Technology', 'Energy-efficient LED backlight for bright, vibrant images while reducing power consumption'],
      ['Versatile Connectivity', 'Multiple input options, including VGA, HDMI, and DC power port, ensuring compatibility with various devices'],
      ['VESA Mount Compatibility', 'Supports VESA mounting, offering flexible installation options for a clean and adjustable setup'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas 22 Inch HD LED Monitor – 16:10, VGA & HDMI, Wide Viewing Angle | BDT 7,600',
      description: 'Buy the Atlas 22-inch HD LED monitor in Bangladesh. 16:10 widescreen, VGA & HDMI input, 5ms response, anti-glare panel. Affordable wide-format monitor at BDT 7,600 with 1-year warranty.',
      keywords: 'Atlas 22 inch monitor Bangladesh, 22 inch HD LED monitor 16:10, widescreen office monitor Bangladesh, VGA HDMI monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-22-hd-led-monitor-1610-aspect-ratio-vga-hdmi-input',
      image: '/assets/images/products/monitor-22-hd-main.png',
    },
  },

  'atlas-19-full-hd-led-monitor-with-hdmi-vga-ports': {
    slug: 'atlas-19-full-hd-led-monitor-with-hdmi-vga-ports',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS 19" Full HD LED Monitor with HDMI & VGA Ports',
    subtitle: 'HD Resolution & Wide Screen - 19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals',
    heroFloat: ['ATS19T', 'Monitor'],
    image: '/assets/images/products/monitor-19-main.png',
    chips: [
      { value: '19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals', label: 'HD Resolution & Wide Screen' },
      { value: '5ms response time for smooth, blur-free visuals, ideal for fast-paced tasks and gaming', label: 'Fast Response Time' },
      { value: 'Reduces reflections and enhances visual comfort, especially during prolonged use', label: 'Anti-Glare Surface' },
    ],
    overviewBody: 'HD Resolution & Wide Screen - 19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals. Fast Response Time - 5ms response time for smooth, blur-free visuals, ideal for fast-paced tasks and gaming. Anti-Glare Surface - Reduces reflections and enhances visual comfort, especially during prolonged use. Multiple Connectivity Options - Includes VGA, HDMI, and DC power input for versatile device compatibility. VESA Mount Compatibility - Supports easy wall mounting, offering flexible installation options to save desk space.',
    overviewStats: [{ value: 'ATS19T', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'HD Resolution & Wide Screen', body: '19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals' },
      { title: 'Fast Response Time', body: '5ms response time for smooth, blur-free visuals, ideal for fast-paced tasks and gaming' },
      { title: 'Anti-Glare Surface', body: 'Reduces reflections and enhances visual comfort, especially during prolonged use' },
    ],
    gallery: [
      { src: '/assets/images/products/monitor-19-main.png', alt: 'ATLAS 19" Full HD LED Monitor - Main View', caption: 'Main View', cls: 'wide' },
      { src: '/assets/images/products/monitor-19-angle.jpg', alt: 'ATLAS 19" Full HD LED Monitor - Side Angle', caption: 'Side Angle', cls: 'tall' },
      { src: '/assets/images/products/monitor-19-detail-1.jpg', alt: 'ATLAS 19" Full HD LED Monitor - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/monitor-19-detail-1.jpg', alt: 'ATLAS 19" Full HD LED Monitor - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'HD Resolution & Wide Screen', items: ['19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals'] },
      { title: 'Fast Response Time', items: ['5ms response time for smooth, blur-free visuals, ideal for fast-paced tasks and gaming'] },
      { title: 'Anti-Glare Surface', items: ['Reduces reflections and enhances visual comfort, especially during prolonged use'] },
      { title: 'Multiple Connectivity Options', items: ['Includes VGA, HDMI, and DC power input for versatile device compatibility'] },
    ],
    specTable: [
      ['SKU', 'ATS19T'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['HD Resolution & Wide Screen', '19-inch display with 1440x900 resolution and a 16:10 aspect ratio for clear and immersive visuals'],
      ['Fast Response Time', '5ms response time for smooth, blur-free visuals, ideal for fast-paced tasks and gaming'],
      ['Anti-Glare Surface', 'Reduces reflections and enhances visual comfort, especially during prolonged use'],
      ['Multiple Connectivity Options', 'Includes VGA, HDMI, and DC power input for versatile device compatibility'],
      ['VESA Mount Compatibility', 'Supports easy wall mounting, offering flexible installation options to save desk space'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas 19 Inch Full HD LED Monitor – HDMI & VGA, 5ms Response | BDT 6,200',
      description: 'Buy the Atlas 19-inch Full HD LED monitor in Bangladesh. 1920×1080 resolution, HDMI & VGA ports, 5ms response time, 16:10 widescreen. Reliable office monitor at BDT 6,200 with 1-year warranty.',
      keywords: 'Atlas 19 inch Full HD monitor Bangladesh, 19 inch LED monitor HDMI VGA, 1920x1080 monitor Bangladesh, affordable FHD monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-19-full-hd-led-monitor-with-hdmi-vga-ports',
      image: '/assets/images/products/monitor-19-main.png',
    },
  },

  'atlas-17-inch-square-led-monitor-hdmi-vga-anti-glare-5ms-response': {
    slug: 'atlas-17-inch-square-led-monitor-hdmi-vga-anti-glare-5ms-response',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS 17 Inch Square LED Monitor HDMI & VGA Support',
    subtitle: 'High-Definition Display - 17-inch screen with 1280x1024 HD resolution for sharp visuals',
    heroFloat: ['ATS17T', 'Monitor'],
    image: '/assets/images/products/monitor-17-square-main.png',
    chips: [
      { value: '17-inch screen with 1280x1024 HD resolution for sharp visuals', label: 'High-Definition Display' },
      { value: '5ms response time for smooth, blur-free visuals during fast-moving scenes', label: 'Fast Response Time' },
      { value: '178 horizontal and vertical viewing angles for consistent image quality from all positions', label: 'Wide Viewing Angle' },
    ],
    overviewBody: 'High-Definition Display - 17-inch screen with 1280x1024 HD resolution for sharp visuals. Fast Response Time - 5ms response time for smooth, blur-free visuals during fast-moving scenes. Wide Viewing Angle - 178 horizontal and vertical viewing angles for consistent image quality from all positions. Anti-Glare Surface - Reduces reflections for comfortable, prolonged use, even in bright environments. Multiple Connectivity Options - Includes VGA, HDMI, and DC power input for versatile device compatibility.',
    overviewStats: [{ value: 'ATS17T', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'High-Definition Display', body: '17-inch screen with 1280x1024 HD resolution for sharp visuals' },
      { title: 'Fast Response Time', body: '5ms response time for smooth, blur-free visuals during fast-moving scenes' },
      { title: 'Wide Viewing Angle', body: '178 horizontal and vertical viewing angles for consistent image quality from all positions' },
    ],
    gallery: [
      { src: '/assets/images/products/monitor-17-square-main.png', alt: 'ATLAS 17 Inch Square LED Monitor - Main View', caption: 'Main View', cls: 'wide' },
      { src: '/assets/images/products/monitor-17-square-angle.jpg', alt: 'ATLAS 17 Inch Square LED Monitor - Side Angle', caption: 'Side Angle', cls: 'tall' },
      { src: '/assets/images/products/monitor-17-square-detail.jpg', alt: 'ATLAS 17 Inch Square LED Monitor - Detail View', caption: 'Detail View', cls: 'full' },
    ],
    specCards: [
      { title: 'High-Definition Display', items: ['17-inch screen with 1280x1024 HD resolution for sharp visuals'] },
      { title: 'Fast Response Time', items: ['5ms response time for smooth, blur-free visuals during fast-moving scenes'] },
      { title: 'Wide Viewing Angle', items: ['178 horizontal and vertical viewing angles for consistent image quality from all positions'] },
      { title: 'Anti-Glare Surface', items: ['Reduces reflections for comfortable, prolonged use, even in bright environments'] },
    ],
    specTable: [
      ['SKU', 'ATS17T'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['High-Definition Display', '17-inch screen with 1280x1024 HD resolution for sharp visuals'],
      ['Fast Response Time', '5ms response time for smooth, blur-free visuals during fast-moving scenes'],
      ['Wide Viewing Angle', '178 horizontal and vertical viewing angles for consistent image quality from all positions'],
      ['Anti-Glare Surface', 'Reduces reflections for comfortable, prolonged use, even in bright environments'],
      ['Multiple Connectivity Options', 'Includes VGA, HDMI, and DC power input for versatile device compatibility'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas 17 Inch Square LED Monitor – HDMI & VGA, Anti-Glare, 5ms | BDT 5,500',
      description: 'Buy the Atlas 17-inch square LED monitor in Bangladesh. HD 4:3 panel, HDMI & VGA inputs, anti-glare coating, 5ms response time. Compact and affordable at BDT 5,500 with 1-year warranty.',
      keywords: 'Atlas 17 inch monitor Bangladesh, 17 inch square LED monitor, 4:3 monitor HDMI VGA, anti-glare monitor Bangladesh, small LED monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-17-inch-square-led-monitor-hdmi-vga-anti-glare-5ms-response',
      image: '/assets/images/products/monitor-17-square-main.png',
    },
  },

  'atlas-ats22vfb100-22-inch-full-hd-100hz-monitor-for-editors-pros': {
    slug: 'atlas-ats22vfb100-22-inch-full-hd-100hz-monitor-for-editors-pros',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS ATS22VFB100 22 Inch Full HD 100Hz Monitor for Editors & Pros',
    subtitle: 'Full HD Display - 22-inch screen with a 1920x1080 resolution for sharp, detailed visuals',
    heroFloat: ['ATS22VFB100', 'Monitor'],
    image: '/assets/images/products/ats22vfb100-main.png',
    chips: [
      { value: '22-inch screen with a 1920x1080 resolution for sharp, detailed visuals', label: 'Full HD Display' },
      { value: 'Smooth motion and reduced blur, perfect for gaming and fast-moving content', label: '100Hz Refresh Rate' },
      { value: '178 horizontal and vertical viewing angles for consistent image quality from all sides', label: 'Wide Viewing Angles' },
    ],
    overviewBody: 'Full HD Display - 22-inch screen with a 1920x1080 resolution for sharp, detailed visuals. 100Hz Refresh Rate - Smooth motion and reduced blur, perfect for gaming and fast-moving content. Wide Viewing Angles - 178 horizontal and vertical viewing angles for consistent image quality from all sides. Multiple Connectivity Options - Includes 1x HDMI and 1x VGA ports for versatile device connections. 3-Year Warranty - Ensures reliable performance and peace of mind with extended protection.',
    overviewStats: [{ value: 'ATS22VFB100', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'Full HD Display', body: '22-inch screen with a 1920x1080 resolution for sharp, detailed visuals' },
      { title: '100Hz Refresh Rate', body: 'Smooth motion and reduced blur, perfect for gaming and fast-moving content' },
      { title: 'Wide Viewing Angles', body: '178 horizontal and vertical viewing angles for consistent image quality from all sides' },
    ],
    gallery: [
      { src: '/assets/images/products/ats22vfb100-main.png', alt: 'ATLAS ATS22VFB100 - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats22vfb100-angle.jpg', alt: 'ATLAS ATS22VFB100 - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats22vfb100-detail-1.jpg', alt: 'ATLAS ATS22VFB100 - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats22vfb100-detail-1.jpg', alt: 'ATLAS ATS22VFB100 - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'Full HD Display', items: ['22-inch screen with a 1920x1080 resolution for sharp, detailed visuals'] },
      { title: '100Hz Refresh Rate', items: ['Smooth motion and reduced blur, perfect for gaming and fast-moving content'] },
      { title: 'Wide Viewing Angles', items: ['178 horizontal and vertical viewing angles for consistent image quality from all sides'] },
      { title: 'Multiple Connectivity Options', items: ['Includes 1x HDMI and 1x VGA ports for versatile device connections'] },
    ],
    specTable: [
      ['SKU', 'ATS22VFB100'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Full HD Display', '22-inch screen with a 1920x1080 resolution for sharp, detailed visuals'],
      ['100Hz Refresh Rate', 'Smooth motion and reduced blur, perfect for gaming and fast-moving content'],
      ['Wide Viewing Angles', '178 horizontal and vertical viewing angles for consistent image quality from all sides'],
      ['Multiple Connectivity Options', 'Includes 1x HDMI and 1x VGA ports for versatile device connections'],
      ['3-Year Warranty', 'Ensures reliable performance and peace of mind with extended protection'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas ATS22VFB100 – 22 Inch Full HD 100Hz Monitor for Editors & Pros | BDT 10,500',
      description: 'Buy the Atlas ATS22VFB100 22-inch Full HD 100Hz monitor in Bangladesh. 1920×1080, HDMI & VGA, flicker-free, ideal for video editing and professional use. BDT 10,500 with 3-year warranty.',
      keywords: 'Atlas ATS22VFB100, 22 inch 100Hz Full HD monitor Bangladesh, monitor for editors Bangladesh, professional monitor 100Hz',
      canonical: 'https://www.atlascomparts.com/atlas-ats22vfb100-22-inch-full-hd-100hz-monitor-for-editors-pros',
      image: '/assets/images/products/ats22vfb100-main.png',
    },
  },

  'atlas-ats22ifw100-pro-series-21-5-ips-100hz-led-monitor-in-white-crisp-visuals': {
    slug: 'atlas-ats22ifw100-pro-series-21-5-ips-100hz-led-monitor-in-white-crisp-visuals',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: 'ATLAS ATS22IFW100 Pro Series 21.5" IPS 100Hz LED Monitor in White Crisp Visuals',
    subtitle: 'Full HD 1920x1080 Resolution - Delivers sharp and detailed visuals for a clear viewing experience',
    heroFloat: ['22IFW100', 'Monitor'],
    image: '/assets/images/products/ats22ifw100-main.png',
    chips: [
      { value: 'Delivers sharp and detailed visuals for a clear viewing experience', label: 'Full HD 1920x1080 Resolution' },
      { value: 'Ensures smooth motion with reduced blur, ideal for gaming and fast-moving content', label: '100Hz Refresh Rate' },
      { value: 'Provides wide 178 viewing angles and consistent color reproduction from any angle', label: 'IPS Panel Technology' },
    ],
    overviewBody: 'Full HD 1920x1080 Resolution - Delivers sharp and detailed visuals for a clear viewing experience. 100Hz Refresh Rate - Ensures smooth motion with reduced blur, ideal for gaming and fast-moving content. IPS Panel Technology - Provides wide 178 viewing angles and consistent color reproduction from any angle. Anti-glare Screen - Reduces reflections and enhances visibility, even in bright environments. VESA Mount Compatibility - Allows flexible mounting options for easy integration into any workspace or setup.',
    overviewStats: [{ value: '22IFW100', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'Full HD 1920x1080 Resolution', body: 'Delivers sharp and detailed visuals for a clear viewing experience' },
      { title: '100Hz Refresh Rate', body: 'Ensures smooth motion with reduced blur, ideal for gaming and fast-moving content' },
      { title: 'IPS Panel Technology', body: 'Provides wide 178 viewing angles and consistent color reproduction from any angle' },
    ],
    gallery: [
      { src: '/assets/images/products/ats22ifw100-main.png', alt: 'ATLAS ATS22IFW100 Pro Series - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats22ifw100-angle.jpg', alt: 'ATLAS ATS22IFW100 Pro Series - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats22ifw100-detail-1.jpg', alt: 'ATLAS ATS22IFW100 Pro Series - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats22ifw100-detail-1.jpg', alt: 'ATLAS ATS22IFW100 Pro Series - Close-up', caption: 'Close-up', cls: '' },
    ],
    specCards: [
      { title: 'Full HD 1920x1080 Resolution', items: ['Delivers sharp and detailed visuals for a clear viewing experience'] },
      { title: '100Hz Refresh Rate', items: ['Ensures smooth motion with reduced blur, ideal for gaming and fast-moving content'] },
      { title: 'IPS Panel Technology', items: ['Provides wide 178 viewing angles and consistent color reproduction from any angle'] },
      { title: 'Anti-glare Screen', items: ['Reduces reflections and enhances visibility, even in bright environments'] },
    ],
    specTable: [
      ['SKU', '22IFW100'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Full HD 1920x1080 Resolution', 'Delivers sharp and detailed visuals for a clear viewing experience'],
      ['100Hz Refresh Rate', 'Ensures smooth motion with reduced blur, ideal for gaming and fast-moving content'],
      ['IPS Panel Technology', 'Provides wide 178 viewing angles and consistent color reproduction from any angle'],
      ['Anti-glare Screen', 'Reduces reflections and enhances visibility, even in bright environments'],
      ['VESA Mount Compatibility', 'Allows flexible mounting options for easy integration into any workspace or setup'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas ATS22IFW100 – 21.5 Inch IPS 100Hz White LED Monitor | BDT 11,500',
      description: 'Buy the Atlas ATS22IFW100 Pro Series 21.5-inch IPS 100Hz monitor in white. Wide viewing angles, Full HD, flicker-free, HDMI & VGA. Premium IPS display in Bangladesh at BDT 11,500.',
      keywords: 'Atlas ATS22IFW100, IPS monitor Bangladesh, 21.5 inch IPS 100Hz monitor, white monitor Full HD, IPS panel monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-ats22ifw100-pro-series-21-5-ips-100hz-led-monitor-in-white-crisp-visuals',
      image: '/assets/images/products/ats22ifw100-main.png',
    },
  },

  'atlas-ats22vfw100-gamers-edition-21-5-100hz-fast-response-gaming-led-monitor': {
    slug: 'atlas-ats22vfw100-gamers-edition-21-5-100hz-fast-response-gaming-led-monitor',
    category: 'Monitor',
    eyebrow: 'Monitor Series',
    title: "ATLAS ATS22VFW100 Gamer's Edition 21.5\" 100Hz Fast-Response Gaming LED Monitor",
    subtitle: 'Full HD 1920x1080 Resolution - Provides crisp, sharp visuals for an immersive viewing experience',
    heroFloat: ['22VFW100', 'Monitor'],
    image: '/assets/images/products/ats22vfw100-main.png',
    chips: [
      { value: 'Provides crisp, sharp visuals for an immersive viewing experience', label: 'Full HD 1920x1080 Resolution' },
      { value: 'Ensures smoother motion, ideal for gaming and fast-moving content', label: '100Hz Refresh Rate' },
      { value: 'Reduces reflections and offers consistent color reproduction from all angles', label: 'Anti-glare VA Panel' },
    ],
    overviewBody: 'Full HD 1920x1080 Resolution - Provides crisp, sharp visuals for an immersive viewing experience. 100Hz Refresh Rate - Ensures smoother motion, ideal for gaming and fast-moving content. Anti-glare VA Panel - Reduces reflections and offers consistent color reproduction from all angles. Versatile Connectivity - Includes VGA, HDMI, and DC power input for easy connection to multiple devices. VESA Mount Compatibility - Allows flexible installation options to fit various workspace setups.',
    overviewStats: [{ value: '22VFW100', label: 'SKU' }, { value: 'Monitor', label: 'Category' }],
    overviewCards: [
      { title: 'Full HD 1920x1080 Resolution', body: 'Provides crisp, sharp visuals for an immersive viewing experience' },
      { title: '100Hz Refresh Rate', body: 'Ensures smoother motion, ideal for gaming and fast-moving content' },
      { title: 'Anti-glare VA Panel', body: 'Reduces reflections and offers consistent color reproduction from all angles' },
    ],
    gallery: [
      { src: '/assets/images/products/ats22vfw100-main.png', alt: "ATLAS ATS22VFW100 Gamer's Edition - Front View", caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/ats22vfw100-angle.jpg', alt: "ATLAS ATS22VFW100 Gamer's Edition - Angle View", caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/ats22vfw100-detail.jpg', alt: "ATLAS ATS22VFW100 Gamer's Edition - Detail View", caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/ats22vfw100-main.png', alt: "ATLAS ATS22VFW100 Gamer's Edition - Overview", caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: 'Full HD 1920x1080 Resolution', items: ['Provides crisp, sharp visuals for an immersive viewing experience'] },
      { title: '100Hz Refresh Rate', items: ['Ensures smoother motion, ideal for gaming and fast-moving content'] },
      { title: 'Anti-glare VA Panel', items: ['Reduces reflections and offers consistent color reproduction from all angles'] },
      { title: 'Versatile Connectivity', items: ['Includes VGA, HDMI, and DC power input for easy connection to multiple devices'] },
    ],
    specTable: [
      ['SKU', '22VFW100'], ['Category', 'Monitor'], ['Availability', 'In stock'],
      ['Full HD 1920x1080 Resolution', 'Provides crisp, sharp visuals for an immersive viewing experience'],
      ['100Hz Refresh Rate', 'Ensures smoother motion, ideal for gaming and fast-moving content'],
      ['Anti-glare VA Panel', 'Reduces reflections and offers consistent color reproduction from all angles'],
      ['Versatile Connectivity', 'Includes VGA, HDMI, and DC power input for easy connection to multiple devices'],
      ['VESA Mount Compatibility', 'Allows flexible installation options to fit various workspace setups'],
    ],
    navBtnText: 'All Monitors',
    navBtnHref: '/monitors',
    meta: {
      title: 'Atlas ATS22VFW100 – 21.5 Inch 100Hz Gaming Monitor Fast Response | BDT 10,500',
      description: "Buy the Atlas ATS22VFW100 Gamer's Edition 21.5-inch 100Hz gaming monitor in Bangladesh. Full HD, fast-response VA panel, HDMI & VGA. Affordable gaming monitor at BDT 10,500 with 3-year warranty.",
      keywords: 'Atlas ATS22VFW100, gaming monitor Bangladesh 100Hz, 21.5 inch gaming monitor, fast response monitor Bangladesh, affordable gaming monitor Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-ats22vfw100-gamers-edition-21-5-100hz-fast-response-gaming-led-monitor',
      image: '/assets/images/products/ats22vfw100-main.png',
    },
  },

  'atlas-raven-h311-v1-motherboard-with-ddr4-m-2-for-intel-6th-9th-gen': {
    slug: 'atlas-raven-h311-v1-motherboard-with-ddr4-m-2-for-intel-6th-9th-gen',
    category: 'Motherboard',
    eyebrow: 'Motherboard Series',
    title: 'ATLAS RAVEN H311 V1 Motherboard with DDR4, M.2 for Intel 6th-9th Gen',
    subtitle: 'Wide CPU Support - Compatible with Intel 6th to 9th Gen processors',
    heroFloat: ['H311V1', 'Motherboard'],
    image: '/assets/images/products/raven-h311-v1-main.png',
    chips: [
      { value: 'Compatible with Intel 6th to 9th Gen processors', label: 'Wide CPU Support' },
      { value: 'Dual-channel DDR4 up to 32GB, speeds reaching 2666MHz', label: 'Fast Memory Performance' },
      { value: 'Supports 4 SATA III ports and 1 M.2 slot', label: 'Flexible Storage Options' },
    ],
    overviewBody: 'Wide CPU Support - Compatible with Intel 6th to 9th Gen processors. Fast Memory Performance - Dual-channel DDR4 up to 32GB, speeds reaching 2666MHz. Flexible Storage Options - Supports 4 SATA III ports and 1 M.2 slot. High-Speed Connectivity - Equipped with USB 3.0, HDMI, Gigabit LAN for fast connections. Enhanced Audio System - Realtek ALC892 chipset delivers immersive 5.1-channel HD sound.',
    overviewStats: [{ value: 'H311V1', label: 'SKU' }, { value: 'Motherboard', label: 'Category' }],
    overviewCards: [
      { title: 'Wide CPU Support', body: 'Compatible with Intel 6th to 9th Gen processors' },
      { title: 'Fast Memory Performance', body: 'Dual-channel DDR4 up to 32GB, speeds reaching 2666MHz' },
      { title: 'Flexible Storage Options', body: 'Supports 4 SATA III ports and 1 M.2 slot' },
    ],
    gallery: [
      { src: '/assets/images/products/raven-h311-v1-main.png', alt: 'ATLAS RAVEN H311 V1 - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/raven-h311-v1-angle.jpg', alt: 'ATLAS RAVEN H311 V1 - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/raven-h311-v1-detail.jpg', alt: 'ATLAS RAVEN H311 V1 - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/raven-h311-v1-main.png', alt: 'ATLAS RAVEN H311 V1 - Overview', caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: 'Wide CPU Support', items: ['Compatible with Intel 6th to 9th Gen processors'] },
      { title: 'Fast Memory Performance', items: ['Dual-channel DDR4 up to 32GB, speeds reaching 2666MHz'] },
      { title: 'Flexible Storage Options', items: ['Supports 4 SATA III ports and 1 M.2 slot'] },
      { title: 'High-Speed Connectivity', items: ['Equipped with USB 3.0, HDMI, Gigabit LAN for fast connections'] },
    ],
    specTable: [
      ['SKU', 'H311V1'], ['Category', 'Motherboard'], ['Availability', 'In stock'],
      ['Wide CPU Support', 'Compatible with Intel 6th to 9th Gen processors'],
      ['Fast Memory Performance', 'Dual-channel DDR4 up to 32GB, speeds reaching 2666MHz'],
      ['Flexible Storage Options', 'Supports 4 SATA III ports and 1 M.2 slot'],
      ['High-Speed Connectivity', 'Equipped with USB 3.0, HDMI, Gigabit LAN for fast connections'],
      ['Enhanced Audio System', 'Realtek ALC892 chipset delivers immersive 5.1-channel HD sound'],
    ],
    navBtnText: 'All Motherboards',
    navBtnHref: '/motherboards',
    meta: {
      title: 'Atlas Raven H311 V1 – Intel 6th–9th Gen DDR4 Micro-ATX Motherboard | BDT 5,460',
      description: 'Buy the Atlas Raven H311 V1 Micro-ATX motherboard for Intel 6th–9th Gen (LGA1151). DDR4 RAM, M.2 NVMe slot, USB 3.0, 4x SATA. Reliable Intel platform at BDT 5,460 in Bangladesh.',
      keywords: 'Atlas Raven H311 V1, Intel H310 motherboard Bangladesh, LGA1151 motherboard DDR4, Intel 6th 9th gen motherboard, Micro ATX Intel motherboard',
      canonical: 'https://www.atlascomparts.com/atlas-raven-h311-v1-motherboard-with-ddr4-m-2-for-intel-6th-9th-gen',
      image: '/assets/images/products/raven-h311-v1-main.png',
    },
  },

  'atlas-raven-b450m-frost-micro-atx-am4-motherboard-with-ryzen-1000-5600-support': {
    slug: 'atlas-raven-b450m-frost-micro-atx-am4-motherboard-with-ryzen-1000-5600-support',
    category: 'Motherboard',
    eyebrow: 'Motherboard Series',
    title: 'ATLAS RAVEN B450M Frost - Micro-ATX AM4 Motherboard with Ryzen 1000-5600 Support',
    subtitle: 'Wide CPU Support - Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket',
    heroFloat: ['MB450', 'Motherboard'],
    image: '/assets/images/products/raven-b450m-frost-main.png',
    heroVideo: '/assets/videos/raven-b450m.mp4',
    chips: [
      { value: 'Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket', label: 'Wide CPU Support' },
      { value: 'Dual DDR4 slots supporting up to 32 GB and 3200 MHz (OC)', label: 'High-Speed Memory' },
      { value: '4 x SATA III ports plus 1 x M.2 slot for SATA & NVMe SSDs', label: 'Flexible Storage Options' },
    ],
    overviewBody: 'Wide CPU Support - Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket. High-Speed Memory - Dual DDR4 slots supporting up to 32 GB and 3200 MHz (OC). Flexible Storage Options - 4 x SATA III ports plus 1 x M.2 slot for SATA & NVMe SSDs. Integrated Display Outputs - HDMI and VGA ports for CPUs with Radeon Graphics. Reliable Connectivity - Gigabit LAN, multiple USB 3.0/2.0 ports, and HD audio.',
    overviewStats: [{ value: 'MB450', label: 'SKU' }, { value: 'Motherboard', label: 'Category' }],
    overviewCards: [
      { title: 'Wide CPU Support', body: 'Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket' },
      { title: 'High-Speed Memory', body: 'Dual DDR4 slots supporting up to 32 GB and 3200 MHz (OC)' },
      { title: 'Flexible Storage Options', body: '4 x SATA III ports plus 1 x M.2 slot for SATA & NVMe SSDs' },
    ],
    gallery: [
      { src: '/assets/images/products/raven-b450m-frost-main.png', alt: 'ATLAS RAVEN B450M Frost - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/raven-b450m-frost-angle.jpg', alt: 'ATLAS RAVEN B450M Frost - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/raven-b450m-frost-detail.jpg', alt: 'ATLAS RAVEN B450M Frost - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/raven-b450m-frost-main.png', alt: 'ATLAS RAVEN B450M Frost - Overview', caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: 'Wide CPU Support', items: ['Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket'] },
      { title: 'High-Speed Memory', items: ['Dual DDR4 slots supporting up to 32 GB and 3200 MHz (OC)'] },
      { title: 'Flexible Storage Options', items: ['4 x SATA III ports plus 1 x M.2 slot for SATA & NVMe SSDs'] },
      { title: 'Integrated Display Outputs', items: ['HDMI and VGA ports for CPUs with Radeon Graphics'] },
    ],
    specTable: [
      ['SKU', 'MB450'], ['Category', 'Motherboard'], ['Availability', 'In stock'],
      ['Wide CPU Support', 'Compatible with AMD Ryzen 1st-5th Gen processors on the AM4 socket'],
      ['High-Speed Memory', 'Dual DDR4 slots supporting up to 32 GB and 3200 MHz (OC)'],
      ['Flexible Storage Options', '4 x SATA III ports plus 1 x M.2 slot for SATA & NVMe SSDs'],
      ['Integrated Display Outputs', 'HDMI and VGA ports for CPUs with Radeon Graphics'],
      ['Reliable Connectivity', 'Gigabit LAN, multiple USB 3.0/2.0 ports, and HD audio'],
    ],
    navBtnText: 'All Motherboards',
    navBtnHref: '/motherboards',
    meta: {
      title: 'Atlas Raven B450M Frost – AMD Ryzen AM4 Micro-ATX Motherboard | BDT 7,700',
      description: 'Buy the Atlas Raven B450M Frost motherboard for AMD Ryzen 1000–5600 (AM4 socket). DDR4, M.2 NVMe, PCIe 3.0, Micro-ATX. Best-value AMD Ryzen board in Bangladesh at BDT 7,700.',
      keywords: 'Atlas Raven B450M Frost, B450M AM4 motherboard Bangladesh, AMD Ryzen motherboard DDR4, Ryzen 5 3600 motherboard, buy B450M motherboard Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-raven-b450m-frost-micro-atx-am4-motherboard-with-ryzen-1000-5600-support',
      image: '/assets/images/products/raven-b450m-frost-main.png',
    },
  },

  'atlas-raven-h61-v3-motherboard-with-ddr3-hdmi-m-2-nvme-slot': {
    slug: 'atlas-raven-h61-v3-motherboard-with-ddr3-hdmi-m-2-nvme-slot',
    category: 'Motherboard',
    eyebrow: 'Motherboard Series',
    title: 'ATLAS RAVEN H61 V3 Motherboard with DDR3, HDMI & M.2 NVMe Slot',
    subtitle: 'Wide CPU Support - Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP)',
    heroFloat: ['H61 V3', 'Motherboard'],
    image: '/assets/images/products/raven-h61-v3-main.png',
    chips: [
      { value: 'Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP)', label: 'Wide CPU Support' },
      { value: 'Supports up to 16 GB DDR3 RAM with speeds up to 1600 MHz', label: 'Efficient Memory Performance' },
      { value: 'HDMI and VGA outputs powered by integrated Intel HD Graphics', label: 'Graphics Ready' },
    ],
    overviewBody: 'Wide CPU Support - Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP). Efficient Memory Performance - Supports up to 16 GB DDR3 RAM with speeds up to 1600 MHz. Graphics Ready - HDMI and VGA outputs powered by integrated Intel HD Graphics. Flexible Storage Options - 4x SATA II ports plus an M.2 NVMe slot (2242 SSD). Stable & Durable Design - Solid capacitors and reinforced PCB ensure reliable long-term performance.',
    overviewStats: [{ value: 'H61 V3', label: 'SKU' }, { value: 'Motherboard', label: 'Category' }],
    overviewCards: [
      { title: 'Wide CPU Support', body: 'Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP)' },
      { title: 'Efficient Memory Performance', body: 'Supports up to 16 GB DDR3 RAM with speeds up to 1600 MHz' },
      { title: 'Graphics Ready', body: 'HDMI and VGA outputs powered by integrated Intel HD Graphics' },
    ],
    gallery: [
      { src: '/assets/images/products/raven-h61-v3-main.png', alt: 'ATLAS RAVEN H61 V3 - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/raven-h61-v3-angle.jpg', alt: 'ATLAS RAVEN H61 V3 - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/raven-h61-v3-detail.jpg', alt: 'ATLAS RAVEN H61 V3 - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/raven-h61-v3-main.png', alt: 'ATLAS RAVEN H61 V3 - Overview', caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: 'Wide CPU Support', items: ['Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP)'] },
      { title: 'Efficient Memory Performance', items: ['Supports up to 16 GB DDR3 RAM with speeds up to 1600 MHz'] },
      { title: 'Graphics Ready', items: ['HDMI and VGA outputs powered by integrated Intel HD Graphics'] },
      { title: 'Flexible Storage Options', items: ['4x SATA II ports plus an M.2 NVMe slot (2242 SSD)'] },
    ],
    specTable: [
      ['Category', 'Motherboard'], ['Availability', 'In stock'],
      ['Wide CPU Support', 'Compatible with Intel 2nd & 3rd Gen Core i7/i5/i3, Pentium, and Celeron processors (up to 95W TDP)'],
      ['Efficient Memory Performance', 'Supports up to 16 GB DDR3 RAM with speeds up to 1600 MHz'],
      ['Graphics Ready', 'HDMI and VGA outputs powered by integrated Intel HD Graphics'],
      ['Flexible Storage Options', '4x SATA II ports plus an M.2 NVMe slot (2242 SSD)'],
      ['Stable & Durable Design', 'Solid capacitors and reinforced PCB ensure reliable long-term performance'],
    ],
    navBtnText: 'All Motherboards',
    navBtnHref: '/motherboards',
    meta: {
      title: 'Atlas Raven H61 V3 – Intel 2nd–3rd Gen DDR3 Motherboard with M.2 NVMe | BDT 2,470',
      description: 'Buy the Atlas Raven H61 V3 budget Intel motherboard. Supports Intel 2nd–3rd Gen (LGA1155), DDR3, M.2 NVMe, HDMI & VGA output. Reliable entry-level board at BDT 2,470 in Bangladesh.',
      keywords: 'Atlas Raven H61 V3, H61 motherboard DDR3 Bangladesh, Intel 2nd 3rd gen motherboard, LGA1155 motherboard HDMI, budget Intel motherboard Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-raven-h61-v3-motherboard-with-ddr3-hdmi-m-2-nvme-slot',
      image: '/assets/images/products/raven-h61-v3-main.png',
    },
  },

  'atlas-raven-h81-v3-reliable-atx-motherboard-for-4th-gen-intel-cpus': {
    slug: 'atlas-raven-h81-v3-reliable-atx-motherboard-for-4th-gen-intel-cpus',
    category: 'Motherboard',
    eyebrow: 'Motherboard Series',
    title: 'ATLAS RAVEN H81 V3- Reliable ATX Motherboard for 4th Gen Intel CPUs',
    subtitle: '4th Gen Intel CPU Support - Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W)',
    heroFloat: ['AT81', 'Motherboard'],
    image: '/assets/images/products/raven-h81-v3-main.png',
    chips: [
      { value: 'Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W)', label: '4th Gen Intel CPU Support' },
      { value: 'Supports up to 16 GB DDR3 RAM (1066/1333/1600 MHz)', label: 'Efficient Memory Performance' },
      { value: 'HDMI and VGA outputs powered by Intel HD Graphics', label: 'Flexible Graphics Options' },
    ],
    overviewBody: '4th Gen Intel CPU Support - Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W). Efficient Memory Performance - Supports up to 16 GB DDR3 RAM (1066/1333/1600 MHz). Flexible Graphics Options - HDMI and VGA outputs powered by Intel HD Graphics. High-Speed Storage - 4 x SATA III ports plus M.2 NVMe (2242) SSD slot. Durable Design - Ultra-stable PCB with solid capacitors for long-lasting reliability.',
    overviewStats: [{ value: 'AT81', label: 'SKU' }, { value: 'Motherboard', label: 'Category' }],
    overviewCards: [
      { title: '4th Gen Intel CPU Support', body: 'Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W)' },
      { title: 'Efficient Memory Performance', body: 'Supports up to 16 GB DDR3 RAM (1066/1333/1600 MHz)' },
      { title: 'Flexible Graphics Options', body: 'HDMI and VGA outputs powered by Intel HD Graphics' },
    ],
    gallery: [
      { src: '/assets/images/products/raven-h81-v3-main.png', alt: 'ATLAS RAVEN H81 V3 - Front View', caption: 'Front View', cls: 'wide' },
      { src: '/assets/images/products/raven-h81-v3-angle.jpg', alt: 'ATLAS RAVEN H81 V3 - Angle View', caption: 'Angle View', cls: 'tall' },
      { src: '/assets/images/products/raven-h81-v3-detail.jpg', alt: 'ATLAS RAVEN H81 V3 - Detail View', caption: 'Detail View', cls: '' },
      { src: '/assets/images/products/raven-h81-v3-main.png', alt: 'ATLAS RAVEN H81 V3 - Overview', caption: 'Overview', cls: '' },
    ],
    specCards: [
      { title: '4th Gen Intel CPU Support', items: ['Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W)'] },
      { title: 'Efficient Memory Performance', items: ['Supports up to 16 GB DDR3 RAM (1066/1333/1600 MHz)'] },
      { title: 'Flexible Graphics Options', items: ['HDMI and VGA outputs powered by Intel HD Graphics'] },
      { title: 'High-Speed Storage', items: ['4 x SATA III ports plus M.2 NVMe (2242) SSD slot'] },
    ],
    specTable: [
      ['SKU', 'AT81'], ['Category', 'Motherboard'], ['Availability', 'In stock'],
      ['4th Gen Intel CPU Support', 'Compatible with Intel Core i7/i5/i3, Pentium, and Celeron processors (up to 95W)'],
      ['Efficient Memory Performance', 'Supports up to 16 GB DDR3 RAM (1066/1333/1600 MHz)'],
      ['Flexible Graphics Options', 'HDMI and VGA outputs powered by Intel HD Graphics'],
      ['High-Speed Storage', '4 x SATA III ports plus M.2 NVMe (2242) SSD slot'],
      ['Durable Design', 'Ultra-stable PCB with solid capacitors for long-lasting reliability'],
    ],
    navBtnText: 'All Motherboards',
    navBtnHref: '/motherboards',
    meta: {
      title: 'Atlas Raven H81 V3 – Intel 4th Gen ATX Motherboard DDR3 | BDT 2,990',
      description: 'Buy the Atlas Raven H81 V3 ATX motherboard for Intel 4th Gen Haswell (LGA1150). Dual DDR3, 4x SATA, VGA & HDMI. Dependable legacy Intel platform at BDT 2,990 in Bangladesh.',
      keywords: 'Atlas Raven H81 V3, H81 ATX motherboard Bangladesh, Intel 4th gen Haswell motherboard, LGA1150 DDR3 motherboard, buy H81 motherboard Bangladesh',
      canonical: 'https://www.atlascomparts.com/atlas-raven-h81-v3-reliable-atx-motherboard-for-4th-gen-intel-cpus',
      image: '/assets/images/products/raven-h81-v3-main.png',
    },
  },
}

export const ALL_SLUGS = Object.keys(PRODUCTS)
